"""Read-only PG correlation for one explicitly authorized public signup test.

No SQL mutation, key plaintext, password or account list is returned. By default
this is offline. The private identity file must be generated by the companion
browser script in the same bounded run.
"""
import argparse
import json
import re
import sys
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path


def require(condition, code):
    if not condition:
        raise RuntimeError(code)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--active-confirmed', action='store_true')
    parser.add_argument('--manifest')
    parser.add_argument('--identity-file')
    parser.add_argument('--expected-sha')
    parser.add_argument('--expected-pg-port', type=int)
    parser.add_argument('--expected-database')
    parser.add_argument('--mode', choices=['preflight', 'inspect', 'cleaned'], default='preflight')
    args = parser.parse_args()
    if not args.active_confirmed:
        print(json.dumps({'status': 'PREPARED_NOT_RUN', 'database_accessed': False}))
        return
    require(all([args.manifest, args.identity_file, args.expected_sha, args.expected_pg_port, args.expected_database]), 'EXPLICIT_TARGET_REQUIRED')
    identity = json.loads(Path(args.identity_file).read_text(encoding='utf-8-sig'))
    login = identity['login']
    require(re.fullmatch(r'ux-public-e2e-\d{8}-[a-f0-9]{16}', login), 'SYNTHETIC_LOGIN_GUARD')
    started = datetime.fromisoformat(identity['started_at'].replace('Z', '+00:00'))
    now = datetime.now(timezone.utc)
    require(now - timedelta(hours=2) < started < now + timedelta(seconds=30), 'BOUNDED_RUN_TIME_GUARD')
    manifest = json.loads(Path(args.manifest).read_text(encoding='utf-8-sig'))
    require(manifest['singlecore_api']['sha'] == args.expected_sha, 'MANIFEST_BINARY_MISMATCH')
    env = json.loads(Path(manifest['singlecore_api']['env_file']).read_text(encoding='utf-8-sig'))
    require(env['DATABASE_HOST'] == '127.0.0.1' and int(env['DATABASE_PORT']) == args.expected_pg_port
            and env['DATABASE_DBNAME'] == args.expected_database, 'EXPLICIT_PG_TARGET_MISMATCH')
    import psycopg
    from psycopg.rows import dict_row
    with psycopg.connect(host=env['DATABASE_HOST'], port=int(env['DATABASE_PORT']), dbname=env['DATABASE_DBNAME'],
                         user=env['DATABASE_USER'], password=env['DATABASE_PASSWORD'], connect_timeout=5,
                         row_factory=dict_row, application_name='realyu-public-signup-readonly',
                         options='-c default_transaction_read_only=on -c statement_timeout=5000 -c lock_timeout=2000') as conn:
        conn.execute('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY')
        require(conn.execute('SELECT phase FROM realyu_migration_state WHERE singleton').fetchone()['phase'] == 'active', 'NATIVE_ACTIVE_REQUIRED')
        rows = conn.execute('''SELECT u.id,u.signup_source,u.balance::text,u.status,u.role,u.deleted_at,u.created_at,
                              i.source_user_id,i.login_name,u.username AS display_name
                         FROM users u JOIN realyu_legacy_identities i ON i.user_id=u.id
                        WHERE i.login_name=%s''', (login,)).fetchall()
        if args.mode == 'preflight':
            require(len(rows) == 0, 'SYNTHETIC_LOGIN_ALREADY_EXISTS')
            print(json.dumps({'pass': True, 'exists': False, 'readonly': True, 'mode': args.mode}))
            return
        if not rows:
            print(json.dumps({'pass': True, 'exists': False, 'readonly': True, 'mode': args.mode}))
            return
        require(len(rows) == 1, 'AMBIGUOUS_IDENTITY')
        user = rows[0]
        require(user['signup_source'] == 'realyu_username' and user['source_user_id'] is None
                and user['created_at'] >= started - timedelta(seconds=5)
                and user['created_at'] <= now and user['deleted_at'] is None and user['role'] == 'user'
                and user['display_name'] == identity['nickname'], 'NEW_SYNTHETIC_IDENTITY_CORRELATION_FAILED')
        if identity.get('user_id'):
            require(user['id'] == identity['user_id'], 'NEW_USER_ID_MISMATCH')
        uid = user['id']
        keys = conn.execute('''SELECT k.id,k.user_id,k.status,k.deleted_at,k.created_at,k.quota_used::text,
                                     k.group_id,s.actor_user_id,s.payer_user_id,s.team_id,
                                     g.status AS group_status,g.subscription_type,g.deleted_at AS group_deleted
                                FROM api_keys k LEFT JOIN realyu_key_scopes s ON s.api_key_id=k.id
                                LEFT JOIN groups g ON g.id=k.group_id WHERE k.user_id=%s ORDER BY k.id''', (uid,)).fetchall()
        require(len(keys) == 1, 'EXACTLY_ONE_NEW_KEY_REQUIRED')
        key = keys[0]
        require(key['user_id'] == uid and key['actor_user_id'] == uid and key['payer_user_id'] == uid
                and key['team_id'] is None and key['deleted_at'] is None
                and key['created_at'] >= started - timedelta(seconds=5)
                and key['group_status'] == 'active' and key['subscription_type'] == 'standard'
                and key['group_deleted'] is None, 'DEFAULT_PERSONAL_KEY_SCOPE_MISMATCH')
        if identity.get('key_id'):
            require(key['id'] == identity['key_id'], 'NEW_KEY_ID_MISMATCH')
        counts = {}
        for name, table, col in [
            ('team_memberships', 'realyu_team_members', 'user_id'),
            ('owned_teams', 'realyu_teams', 'owner_user_id'),
            ('stock_subscriptions', 'user_subscriptions', 'user_id'),
            ('managed_subscriptions', 'realyu_funding_subscriptions', 'user_id'),
            ('orders', 'payment_orders', 'user_id'),
            ('funding_requests', 'realyu_funding_requests', 'actor_user_id'),
            ('usage_logs', 'usage_logs', 'user_id'),
        ]:
            counts[name] = conn.execute(f'SELECT count(*) AS n FROM {table} WHERE {col}=%s', (uid,)).fetchone()['n']
        counts['purchase_grants'] = conn.execute('''SELECT count(*) AS n FROM realyu_purchase_grants g
              JOIN realyu_purchase_snapshots s ON s.order_id=g.order_id WHERE s.actor_user_id=%s''', (uid,)).fetchone()['n']
        # Return financial invariants independently of identity correlation: an
        # unexpected grant must fail acceptance, yet must not prevent safe
        # cleanup of this exact newly created synthetic identity.
        zero_balance = Decimal(user['balance']) == 0
        zero_key_usage = Decimal(key['quota_used']) == 0
        if args.mode == 'cleaned':
            require(user['status'] == 'disabled' and key['status'] == 'inactive', 'CLEANUP_NOT_COMPLETE')
        else:
            require(user['status'] in ('active', 'disabled') and key['status'] in ('active', 'inactive'), 'UNEXPECTED_NEW_ENTITY_STATUS')
        print(json.dumps({'pass': True, 'exists': True, 'readonly': True, 'mode': args.mode,
                          'user_id': uid, 'key_id': key['id'], 'signup_source': user['signup_source'],
                          'source_user_id_null': True, 'identity_matches': True,
                          'created_at': user['created_at'].isoformat(), 'user_status': user['status'],
                          'key_status': key['status'], 'key_count': 1, 'personal_scope': True,
                          'zero_balance': zero_balance, 'zero_key_usage': zero_key_usage, 'counts': counts}))


if __name__ == '__main__':
    try:
        main()
    except Exception as error:
        code = str(error) if type(error) is RuntimeError and re.fullmatch(r'[A-Z0-9_]+', str(error)) else type(error).__name__
        print(json.dumps({'pass': False, 'error_code': code, 'readonly': True}))
        sys.exit(1)
